# Generated by Django 4.2.11 on 2024-03-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resumelink', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverletter', models.TextField()),
                ('appdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('hired', 'Pending'), ('interviewing', 'Interviewing'), ('applied', 'Applied')], default='applied', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobseeker')),
            ],
        ),
    ]
